# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [3]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [8]:
# Import torch
import torch

# Create random tensor
rand_tensor = torch.rand(size=(7, 7))
rand_tensor

tensor([[0.9256, 0.0222, 0.4170, 0.7848, 0.0642, 0.7639, 0.0236],
        [0.9945, 0.0529, 0.3450, 0.9679, 0.6454, 0.3482, 0.6977],
        [0.4060, 0.5557, 0.6930, 0.9045, 0.6229, 0.9642, 0.0673],
        [0.6158, 0.2753, 0.5725, 0.5619, 0.2339, 0.3291, 0.2268],
        [0.5833, 0.2578, 0.0151, 0.1720, 0.8202, 0.0461, 0.4942],
        [0.3641, 0.4446, 0.2292, 0.1622, 0.3249, 0.0159, 0.9561],
        [0.6914, 0.3584, 0.3502, 0.2196, 0.8595, 0.8208, 0.1174]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [20]:
# Create another random tensor
tensor_2 = torch.rand(size=(1, 7)).t()
# Perform matrix multiplication
torch.transpose(tensor_2, 0, 1)

tensor([[0.3909, 0.7306, 0.7549, 0.9661, 0.1284, 0.5150, 0.2939]])

In [21]:
tensor_2.t()

tensor([[0.3909, 0.7306, 0.7549, 0.9661, 0.1284, 0.5150, 0.2939]])

In [27]:
mat_mul = rand_tensor @ tensor_2
mat_mul

tensor([[1.8596],
        [2.0901],
        [2.5580],
        [1.6831],
        [0.8682],
        [1.1277],
        [1.5762]])

In [26]:
torch.mm(rand_tensor, tensor_2)

tensor([[1.8596],
        [2.0901],
        [2.5580],
        [1.6831],
        [0.8682],
        [1.1277],
        [1.5762]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [31]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_1 = torch.rand(size=(7, 7))
tensor_2 = torch.rand(size=(7, 1))
tensor_1 @ tensor_2

# Matrix multiply tensors


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [36]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
